"""Search candidates for unmatched (item, store) pairs and render them as YAML comments."""

from __future__ import annotations

import logging
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime

from supermercado.config import AppConfig
from supermercado.domain.matching import filter_candidates
from supermercado.domain.models import Listing
from supermercado.pipeline.collect import StoreFailure
from supermercado.stores.base import StoreAdapter

log = logging.getLogger(__name__)
MARKER = (
    "# --- match proposals (generated by `python -m supermercado propose`; "
    "move approved entries above this line) ---"
)
MANUAL_NOTE = "# lider: no automated search, its matches are manual (sku + url by hand)."


@dataclass(frozen=True)
class Proposal:
    item_id: str
    store: str
    listing: Listing
    unit_price: int
    unit: str


def propose(
    config: AppConfig,
    adapters: Mapping[str, StoreAdapter],
    *,
    now: datetime,
    max_per_pair: int = 3,
) -> tuple[list[Proposal], list[StoreFailure]]:
    proposals: list[Proposal] = []
    failures: list[StoreFailure] = []
    for store_id, adapter in adapters.items():
        if not adapter.supports_search:
            continue
        for item in config.basket:
            if store_id in config.matches.get(item.id, {}):
                continue
            try:
                listings = adapter.search(item.search)
            except Exception as exc:  # a failing store must not stop the others
                log.warning("%s search failed: %s", store_id, exc)
                failures.append(StoreFailure(store_id, type(exc).__name__, str(exc), now))
                break
            for listing, unit_price in filter_candidates(item, listings)[:max_per_pair]:
                proposals.append(Proposal(item.id, store_id, listing, unit_price, item.unit.value))
    return proposals, failures


def _clp(amount: int) -> str:
    return f"${amount:,}".replace(",", ".")


def _one_line(text: str) -> str:
    return " ".join(text.split())


def _line(proposal: Proposal, today: date) -> str:
    listing = proposal.listing
    entry = f'{{ sku: "{listing.sku}", size: {listing.size:g}, approved: {today.isoformat()} }}'
    price = _clp(listing.promo_price or listing.price or 0)
    note = " | ".join(
        part
        for part in (
            _one_line(listing.name),
            _one_line(listing.brand or ""),
            f"{price} -> {_clp(proposal.unit_price)}/{proposal.unit}",
            listing.url or "",
        )
        if part
    )
    return f"#   {proposal.store}: {entry}  # {note}"


def render_proposals(
    matches_text: str, proposals: Sequence[Proposal], *, week: str, today: date
) -> str:
    head = matches_text.split(MARKER, 1)[0].rstrip("\n")
    if not proposals:
        return f"{head}\n" if head else ""
    lines = [head, ""] if head else []
    lines += [MARKER, f"# week: {week}", MANUAL_NOTE]
    grouped: dict[str, list[Proposal]] = {}
    for proposal in proposals:
        grouped.setdefault(proposal.item_id, []).append(proposal)
    for item_id, group in grouped.items():
        lines.append(f"# {item_id}:")
        lines += [_line(proposal, today) for proposal in group]
    return "\n".join(lines) + "\n"


def render_pr_body(
    proposals: Sequence[Proposal],
    failures: Sequence[StoreFailure],
    manual_stores: Sequence[str],
) -> str:
    lines = [
        f"{len(proposals)} candidate matches generated by `python -m supermercado propose`, "
        "cheapest unit price first.",
        "",
        "To approve one, move its entry above the marker in `config/matches.yaml`, remove the "
        "leading `# `, and keep at most one SKU per item and store (duplicate keys are rejected). "
        "Delete the rest of the generated section before merging.",
    ]
    if manual_stores:
        names = ", ".join(manual_stores)
        lines += [
            "",
            f"{names}: no automated search, its matches are manual (add sku and url by hand).",
        ]
    if failures:
        lines += ["", "Stores that failed during the search (no candidates from them this week):"]
        lines += [
            f"- {failure.store}: {failure.error_class}: {_one_line(failure.message)}"
            for failure in failures
        ]
    return "\n".join(lines) + "\n"
